#! /usr/bin/env perl
use strict;
use warnings;

use Test::More tests => 5;

my $code_file = 'code';
$ENV{PERL6LIB} = 'lib';
my $perl6 = $ENV{PERL6EXECUTABLE} || 'perl6';

sub run {
    my ($input) = @_;

    open my $INPUT, '>', 'input';
    print {$INPUT} $input;
    close $INPUT;

    my $output = `$perl6 $code_file < input 2>&1`;
    unlink 'input';

    return $output;
}

die qq[NO FILE "$code_file"]
    unless -e $code_file;

die qq[\nFILE "$code_file" DOES NOT COMPILE]
    if system("$perl6 -c $code_file > /dev/null");

is run(""), "0\n";
is run("bzzt\n"), qq[Unrecognized line: "bzzt"\n];

is run(<<'INPUT'), "1\n";
(0, -1, 0)
(0, 0, -1)
(-1, 0, 0)
(0, 0, 1)
(1, 0, 0)
INPUT

is run(<<'INPUT'), "2\n";
(0, -2, 0)
(0, -1, -1)
(-1, -1, 0)
(0, -1, 1)
(1, -1, 0)
(0, 0, -1)
(-1, 0, 0)
(0, 0, 1)
(1, 0, 0)
INPUT

is run(<<'INPUT'), "1\n";
(0, -2, 0)
(0, -1, -1)
(-1, -1, 0)
(0, -1, 1)
(1, -1, 0)
(0, 0, -1)
(0, 0, 1)
(1, 0, 0)
INPUT
