#! /usr/bin/env perl
use strict;
use warnings;

use Test::More tests => 2;

my $code_file = 'code';
$ENV{PERL6LIB} = 'lib';
my $perl6 = $ENV{PERL6EXECUTABLE} || 'perl6';

sub run {
    my ($param) = @_;

    my $output = `$perl6 $code_file $param 2>&1`;
    return $output;
}

sub trim_trailing_space {
    my ($line) = @_;
    $line =~ s/ +$//;
    return $line;
}

sub trim_trailing_spaces {
    my ($text) = @_;
    return join "",
        map { trim_trailing_space($_) . "\n" }
        split "\n", $text;
}

die qq[NO FILE "$code_file"]
    unless -e $code_file;

die qq[\nFILE "$code_file" DOES NOT COMPILE]
    if system("$perl6 -c $code_file > /dev/null");

is trim_trailing_spaces(run("0123456789")), <<'OUTPUT';
0 __ 0

1 __ 1

2 __ 2

3 __ 3

4 __ 4

5 __ 5

6 __ 6

7 __ 7

8 __ 8

9 __ 9
OUTPUT

is trim_trailing_spaces(run("0123456798")), <<'OUTPUT';
0 ____ 0

1 ____ 1

2 ____ 2

3 ____ 3

4 ____ 4

5 ____ 5

6 ____ 6

7 ____ 7

8 _  _ 9
   \/
9 _/\_ 8
OUTPUT
